<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Legal</title>
<link href="stylesheets/legal.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="legal_container">
<div class="logo_holder"><a href="index.php"><img src="images/legal_logo.png" width="145" height="45" alt="Blackbull Logo"/></a></div>
<div id="legal_holder">
<h1>&nbsp;legal</h1>
<h2>© Copyright 2010 Blackbull Investment Company | All rights reserved</h2>
<h3>Disclaimer:</h3>
<p>The information that this site holds is believed to be authentic but implied to no warranties of any kind. The material presented on this website is thought to be totally accurate, correct, reliable, and profitable.  Blackbull Investment Company doesn't warrant any compensation or representations for the materials used that are readily available at this website or the sources and links of the same. Blackbull Investment Company puts its best efforts to provide the best services to its clients in both the investment education and tools. Any kind of losses will not be the responsibility of Blackbull Investment Company. The trading and the investment positions published on the website are some of the positions Blackbull Investment Company holds. These positions are the showcase of our performance and bare no responsibility for the use of them by any person or institution. The fees paid for the services, tools and seminar are totally on the will of the prospect customer to select the service and subscribe for it. Hence, refund of any kind is not warrantied under any circumstances.</p>
<h3>Privacy Policy:</h3>
<p>Blackbull Investment Company is fully committed to safeguard your personal information. We must obtain some basic personal information like Name, address, telephone number, Email address etc. from you to provide you with the services. This information is helpful to both Blackbull Investment Company and you to fetch services easily and to contact you in time. From time to time, we may request your valuable feedback for the evaluation of the services. We might invite you to actively participate in polls or surveys that may be posted on our website or mailed to you directly. Participation in survey or polls is completely voluntary.</p><p>We only use your personal information to provide you the service at your account, to take your feedbacks, to take suggestions regarding any improvements, and to update you about additional products or services that may be of interest to you.</p><p>We do not leak your personal information to third parties who does spamming. We however, may share selected information under certain
conditions as part of normal business operations under confidentiality agreements.</p><p>Our site may contain links to other Web sites. Blackbull Investment Company is not responsible for the privacy practices or the content of such Web sites.</p>
<h3>Terms of Use:</h3>
<p>By visiting our site you are agreeing to be bound by the following terms and conditions. We may change these terms and conditions at any time. Your continued use of Blackbull Investment Company's website means that you accept any new or modified terms and conditions that we come up with. Please re-visit the `Terms of Use' page at our site from time to time to stay abreast of any changes that we may introduce.</p><p>The term Blackbull Investment Company is used through this entire Terms of Use document to refer to the website, its owners and the employees and associates of the owners.</p>
<h4>registration:</h4>
<p>By registering, you certify that all information you provide, now or in the future, is accurate.</p><p>Blackbull Investment Company reserves the right, in its sole discretion, to deny you access to this website or any portion thereof without notice for the following reasons:</p>
<ol>
<li>immediately by Blackbull Investment Company for any unauthorized access or use by you.</li>
<li>immediately by Blackbull Investment Company if you assign or transfer (or attempt the same) any rights granted to you under this Agreement.</li>
<li>immediately, if you violate any of the other terms and conditions of this User Agreement.</li>
</ol>
<h4>license:</h4>
<p>Blackbull Investment Company, hereby grants you a limited, non-exclusive, non-assignable and non-transferable license to access Blackbull Investment Company's website provided and expressly conditioned upon your agreement that all such access and use shall be governed by all of the terms and conditions set forth in this USER AGREEMENT.</p>
<h4>copyright:</h4>
<p>Blackbull Investment Company's website as well as the design and information contained in this website is the valuable, exclusive property of Blackbull Investment Company, and nothing in this Agreement shall be construed as transferring or assigning any such ownership rights to you or any other person or entity. All portfolio positions on our website are the proprietary, confidential property of Blackbull Investment Company and cannot be repeated for any reason outside this website. You agree not to repeat or rebroadcast in any way any of the information made available on Blackbull Investment Company's website for any reason whatsoever. You agree that if you do repeat or re-post any of the information made available on Blackbull Investment Company's website by any mean, you will be liable for actual and punitive damages as determined by Blackbull Investment Company and additional damages to be determined by a Indian court of Law.</p><p>You may not resell, redistribute, broadcast or transfer the information or use the information in a searchable, machine-readable database unless separately and specifically authorized in writing by Blackbull Investment Company prior to such use. You may not rent, lease, sublicense, distribute, transfer, copy, reproduce, publicly display, publish, adapt, store or time-share Blackbull Investment Company's website, any part thereof, or any of the information received or accessed therefrom to or through any other person or entity unless separately and specifically authorized in writing by Blackbull Investment Company prior to such use. In addition, you may not remove, alter or obscure any copyright, legal or proprietary notices in or on any portions of Blackbull Investment Company's website without prior written authorization. Except as set forth herein, any other use of the information contained in this site requires the prior written consent of Blackbull Investment Company's website and may require a separate fee.</p>
<h4>delays in service:</h4>
<p>Blackbull Investment Company (including its and their directors, employees, affiliates, agents, representatives or subcontractors) shall not be liable for any loss or liability resulting, directly or indirectly, from delays or interruptions due to electronic or mechanical equipment failures, telephone interconnect problems, defects, weather, strikes, walkouts, fire, acts of God, riots, armed conflicts, acts of war, or other like causes. Blackbull Investment Company shall have no responsibility to provide you access to Blackbull Investment Company's website while interruption of Blackbull Investment Company's website is due to any such cause shall continue.</p>
<h4>liability disclaimer:</h4>
<p class="allcaps">you expressly agree that use of the website is at your sole risk.</p>
<p class="allcaps">the content, information, software, products, features and services published on this web site may include inaccuracies or typographical errors. changes are periodically added to the content herein. Blackbull Investment Company may make improvements and/or changes in this web site at any time. this web site may be temporarily unavailable from time to time due to required maintenance, telecommunications interruptions, or other disruptions. Blackbull Investment Company (and its owners, suppliers, consultants, advertisers, affiliates, partners, employees or any other associated entities, all collectively referred to as associated entities hereafter) shall not be liable to user or member or any third party should Blackbull Investment Company exercise its right to modify or discontinue any or all of the content, information, software, products, features and services published on this website.</p>
<p class="allcaps">Blackbull Investment Company and/or its respective associated entities make no representations about the suitability of the content, information, software, products, features and services contained on this web site for any purpose. all such content, information, software, products, features and services are provided "as is" without warranty of any kind. Blackbull Investment Company and/or its associated entities hereby disclaim all warranties and conditions with regard to these content, information, software, products, features and services, including all implied warranties and conditions of merchantability, fitness for a particular purpose, title, non-infringement, and availability.</p>
<p class="allcaps">in no event shall Blackbull Investment Company and/or its associated entities be liable for any direct, indirect, punitive, incidental, special or consequential damages arising out of or in any way connected with the use of this web site or with the delay or inability to use this website, or for any content, information, software, products, features and services obtained through this web site, or otherwise arising out of the use of this web site, whether based on contract, tort, strict liability or otherwise, even if Blackbull Investment Company or any of its associated entities has been advised of the possibility of damages.</p>
<h4>information disclaimer:</h4>
<p>You acknowledge that the information provided through Blackbull Investment Company is compiled from sources, which are beyond the control of Blackbull Investment Company. Though such information is recognized by the parties to be generally reliable, the parties acknowledge that inaccuracies may occur and Blackbull Investment Company does not warrant the accuracy or suitability of the information. For this reason, as well as the possibility of human and mechanical errors and other factors, YOU ACKNOWLEDGE THAT BLACKBULL INVESTMENT COMPANY'S WEBSITE IS PROVIDED TO YOU ON AN "AS IS, WITH ALL FAULTS" BASIS. BLACKBULL INVESTMENT COMPANY EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, WHETHER EXPRESS, ORAL, IMPLIED, STATUTORY OR OTHERWISE, OF ANY KIND TO THE USERS AND/OR ANY THIRD PARTY, INCLUDING ANY IMPLIED WARRANTIES OF ACCURACY, TIMELINESS, COMPLETENESS, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AS WELL AS ANY WARRANTIES ARISING BY VIRTUE OF CUSTOM OF TRADE OR COURSE OF DEALING AND ANY IMPLIED WARRANTIES OF TITLE OR NON-INFRINGEMENT. IN ADDITION, BLACKBULL INVESTMENT COMPANY, IN PROVIDING THE INFORMATION MAKES NO ENDORSEMENT OF ANY PARTICULAR SECURITY, MARTKET PARTICIPANT, OR BROKERAGE. FURTHER, BLACKBULL INVESTMENT COMPANY DOES NOT REPRESENT OR WARRANT THAT IT WILL MEET YOUR REQUIREMENTS OR IS SUITABLE FOR YOUR NEEDS.</p>
<p>Under this User Agreement, you assume all risk of errors and/or omissions in Blackbull Investment Company's website, including the transmission or translation of information. You assume full responsibility for implementing sufficient procedures and checks to satisfy your requirements for the accuracy and suitability of Blackbull Investment Company's website, including the information, and for maintaining any means, which you may require for the reconstruction of lost data or subsequent manipulations or analyses of the information under the User Agreement.</p>
<p class="allcaps">you agree that Blackbull Investment Company (including its and their officers, directors, employees, affiliates, group companies agents, representatives or subcontractors) shall not in any event be liable for any special, incidental or consequential damages arising out of the use or inability to use Blackbull Investment Company's website for any purpose whatsoever. Blackbull Investment Company and it's affiliates, officers, directors, employees and agents shall have no liability in tort, contract, or otherwise to user and/or any third party.</p>
<h4>links to third party sites:</h4>
<p>The linked sites are not under the control of Blackbull Investment Company. Blackbull Investment Company has not reviewed, nor approved these sites and is not responsible for the content or omissions of any linked site or any links contained in a linked site. The inclusion of any linked site does not imply endorsement by Blackbull Investment Company. Third party links to Blackbull Investment Company shall be governed by a separate agreement.</p>
<h4>Indemnification:</h4>
<p class="allcaps">you shall indemnify, defend and hold harmless Blackbull Investment Company (including its and their officers, directors, employees, affiliates, group companies, agents, representatives or subcontractors) from any and all claims and losses imposed on, incurred by or asserted as a result of or related to:</p>
<ol class="allcaps">
<li>your access and use of Blackbull Investment Company's website.</li>
<li>any non-compliance by user with the terms and conditions hereof.</li>
<li>any third party actions related to users receipt and use of the information, whether authorized or unauthorized.</li>
</ol>
<p>Any clause declared invalid shall be deemed severable and not affect the validity or enforceability of the remainder. These terms may only be amended in a writing signed by Blackbull Investment Company.</p>
<h4>conflicting terms:</h4>
<p>If there is any conflict between this User Agreement and other documents, this User Agreement shall govern, whether such order or other documents is prior to or subsequent to this User Agreement, or is signed or acknowledged by any director, officer, employee, representative or agent of Blackbull Investment Company.</p>
<h4>Attorney's fees:</h4>
<p>If Blackbull Investment Company takes action (by itself or through its associate companies) to enforce any of the provisions of this User Agreement, including collection of any amounts due hereunder, Blackbull Investment Company shall be entitled to recover from you (and you agree to pay), in addition to all sums to which it is entitled or any other relief, at law or in equity, reasonable and necessary attorney's fees and any costs of any litigation.</p>
<h4>general agreement:</h4>
<p>This User Agreement constitutes the general agreement between the parties, and no other agreement, written or oral, exists between you and Blackbull Investment Company. By using the Information on Blackbull Investment Company's website, you assume full responsibility for any and all gains and losses, financial, emotional or otherwise, experienced, suffered or incurred by you. Blackbull Investment Company does not guarantee the accuracy, completeness or timeliness of, or otherwise endorse in any way, the views, opinions or recommendations expressed in the Information, does not give investment advice, and does not advocate the purchase or sale of any security or investment by you or any other individual. The Information is not intended to provide tax, legal or investment advice, which you should obtain from your professional advisor prior to making any investment of the type discussed in the Information. The Information does not constitute a solicitation by the information providers, Blackbull Investment Company or other of the purchase or sale of securities.</p>
<p class="allcaps">the service is provided "as is," without warranty of any kind, either express or implied, including without limitation, any warranty for information, data, services, uninterrupted access, or products provided through or in connection with the service. specifically, Blackbull Investment Company disclaims any and all warranties, including, but not limited to:</p>
<ol class="allcaps">
<li>any warranties concerning the availability, accuracy, usefulness, or content of information, products or services.</li>
<li>any warranties of title, warranty of non-infringement, warranties of merchantability or fitness for a particular purpose.</li>
</ol>
<p class="allcaps">this disclaimer of liability applies to any damages or injury caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of record, whether for breach of contract, tort, negligence, or under any other cause of action.</p>
<p class="allcaps">neither Blackbull Investment Company nor any of its employees, agents, successors, assigns, affiliates, group companies or content or service providers shall be liable to you or other third party for any direct, indirect, incidental, special or consequential damages arising out of use of service or inability to gain access to or use the service or out of any breach of any warranty. because some countries do not allow the exclusion or limitation of liability for consequential or incidental damages, the above limitation may not apply to you. in such countries, the respective liability of Blackbull Investment Company, its employees, agents, successors, assigns, affiliates, group companies and content or service providers respective liability is limited to the amount provided under said law. further, you agree and understand that all services provided are non-refundable and that you should carefully consider whether our services are able to meet your needs.</p>
<h4>termination:</h4>
<p>This User Agreement and the license rights granted hereunder shall remain in full force and effect unless terminated or canceled for any of the following reasons:</p>
<ol>
<li>immediately by Blackbull Investment Company for any unauthorized access or use by you</li>
<li>immediately by Blackbull Investment Company if you assign or transfer (or attempt the same) any rights granted to you under this Agreement</li>
<li>immediately, if you violate any of the other terms and conditions of this User Agreement.</li>
</ol>
<p>Termination or cancellation of this Agreement shall not effect any right or relief to which Blackbull Investment Company may be entitled, at law or in equity. Upon termination of this User Agreement, all rights granted to you will terminate and revert to Blackbull Investment Company. Except as set forth herein, regardless of the reason for cancellation or termination of this User Agreement, the fee charged if any for access to Blackbull Investment Company is non-refundable for any reason.</p>
<h4>jurisdiction:</h4>
<p>The terms of this agreement are exclusively based on and subject to Indian law. You hereby consent to the exclusive jurisdiction and venue of courts in Mumbai, India in all disputes arising out of or relating to the use of this website. Use of this website is unauthorized in any jurisdiction that does not give effect to all provisions of these terms and conditions.</p>
<h1>end of legal</h1>
</div>
<div class="logo_holder"><a href="index.php"><img src="images/legal_logo.png" width="145" height="45" alt="Blackbull Logo"/></a></div>
</div>
</body>
</html>