<h2>How to make sense of the markets?</h2>
<p>The market is a difficult animal to understand. A chaos that is not easy to unravel. As an anecdote, the famous physician and mathematician Newton lost his fortune during the South Sea Bubble in the stock markets. In fact, the whole science of investing is barely 70 years old compared to other fields like Economics that have a history stretching back centuries.</p>
<p>However, we do have some sound theories and principals that always allow a prudent and alert investor to benefit from the markets. Over this series of articles, BlackBull will try and introduce you to certain concepts that will help you to understand investing better and make informed decisions.</p>
<p>The beginning of a successful investing career begins with a deep understanding of one's own self. Each individual is different. Yet, if we run a scan on a diverse sample of retail portfolios, we will find similar stocks. The reason for this fallacy is lack of understanding of risk.</p>
<p>Risk is its most basic form is the occurrence of an unfavourable event. The loss due to such an event depends on two factors - the probability or likelihood of the event occurring and the magnitude of the loss. Therefore, individuals intuitively weigh the risk in their minds before committing to any action. The good news is that humans have a very good intuitive capability for most occasions based on their life experiences. We hardly go wrong in choosing the right house, the right meal... I may not say the same about the right spouse!!</p>
<p>So, the clear irony is that most retail investors do not have an intuition for investing. And the bigger fallacy is that we do not want to invest time in developing that intuition. It cannot be stressed enough that most successful investors spend majority of their time developing the intuition.</p>
<p>So, let&#8217;s take this one step further. Most of retail investors are employed in different jobs or industries. They spend considerable time in understanding their jobs and are very good at understanding the cycles of that industry. For example, a doctor knows before anybody else as to which drug will be the next blockbuster. A construction worker knows if the activity is heating up or cooling down.</p>
<p>All that takes from here is to follow this understanding of the business and invest. When a doctor knows the next big drug, he can buy stocks in the company that makes that drug. When a construction worker knows the activity heating up, he can buy the stock in the realty company.</p>
<p>But ironically, the doctor will buy oil stocks and the construction worker will buy IT hot scrips. I hope you can see the dilemma and the helplessness of such investment decisions.</p>
<p class="last">The golden adage of Investing has always been: KNOW THYSELF!!</p>